-- VTS Energy & Security V2 Supabase schema
create extension if not exists pgcrypto;

-- Admin users table
create table if not exists public.admin_users(
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz default now()
);

-- Site settings table
create table if not exists public.site_settings(
  id bigint primary key default 1 check(id=1),
  company_name text not null,
  legal_name text not null,
  registration_number text not null,
  phone text not null,
  phone2 text,
  whatsapp text,
  sales_email text not null,
  info_email text not null,
  address text not null,
  coverage text,
  mission text,
  vision text,
  values text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Categories table
create table if not exists public.categories(
  id bigint generated by default as identity primary key,
  name text unique not null,
  active boolean default true,
  display_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Products table
create table if not exists public.products(
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  category_id bigint references public.categories(id) on delete set null,
  category text,
  short_description text,
  description text not null,
  price numeric,
  price_type text default 'per unit',
  promotion_status text default 'none',
  promotion_type text default 'on_sale',
  original_price numeric,
  sale_price numeric,
  image_url text,
  features jsonb,
  specifications jsonb,
  active boolean default true,
  featured boolean default false,
  display_order int default 0,
  is_demo boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.products add column if not exists specifications jsonb;
alter table public.products add column if not exists promotion_status text default 'none';
alter table public.products add column if not exists promotion_type text default 'on_sale';
alter table public.products add column if not exists original_price numeric;
alter table public.products add column if not exists sale_price numeric;

-- Services table
create table if not exists public.services(
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null check(category in('Energy Solutions','Digital Security Solutions')),
  description text not null,
  display_order int default 0,
  image text,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Admin function
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_users where user_id=auth.uid());
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon,authenticated;

-- Enable RLS
alter table public.admin_users enable row level security;
alter table public.site_settings enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.services enable row level security;

-- RLS Policies for admin_users
drop policy if exists admin_users_select on public.admin_users;
create policy admin_users_select on public.admin_users for select to authenticated using(user_id=auth.uid());

-- RLS Policies for site_settings
drop policy if exists settings_public_read on public.site_settings;
create policy settings_public_read on public.site_settings for select to anon,authenticated using(true);

drop policy if exists settings_admin_update on public.site_settings;
create policy settings_admin_update on public.site_settings for update to authenticated using(public.is_admin()) with check(public.is_admin());

-- RLS Policies for categories
drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories for select to anon,authenticated using(active=true or public.is_admin());

drop policy if exists categories_admin_insert on public.categories;
create policy categories_admin_insert on public.categories for insert to authenticated with check(public.is_admin());

drop policy if exists categories_admin_update on public.categories;
create policy categories_admin_update on public.categories for update to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists categories_admin_delete on public.categories;
create policy categories_admin_delete on public.categories for delete to authenticated using(public.is_admin());

-- RLS Policies for products
drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products for select to anon,authenticated using(active=true or public.is_admin());

drop policy if exists products_admin_insert on public.products;
create policy products_admin_insert on public.products for insert to authenticated with check(public.is_admin());

drop policy if exists products_admin_update on public.products;
create policy products_admin_update on public.products for update to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists products_admin_delete on public.products;
create policy products_admin_delete on public.products for delete to authenticated using(public.is_admin());

-- RLS Policies for services
drop policy if exists services_public_read on public.services;
create policy services_public_read on public.services for select to anon,authenticated using(active=true or public.is_admin());

drop policy if exists services_admin_insert on public.services;
create policy services_admin_insert on public.services for insert to authenticated with check(public.is_admin());

drop policy if exists services_admin_update on public.services;
create policy services_admin_update on public.services for update to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists services_admin_delete on public.services;
create policy services_admin_delete on public.services for delete to authenticated using(public.is_admin());

-- Storage bucket
insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do update set public=true;

drop policy if exists product_images_public_read on storage.objects;
create policy product_images_public_read on storage.objects for select to public using(bucket_id='product-images');

drop policy if exists product_images_authenticated_insert on storage.objects;
create policy product_images_authenticated_insert on storage.objects for insert to authenticated with check(bucket_id='product-images' and public.is_admin());

drop policy if exists product_images_authenticated_delete on storage.objects;
create policy product_images_authenticated_delete on storage.objects for delete to authenticated using(bucket_id='product-images' and public.is_admin());

-- Seed data
insert into public.site_settings(id,company_name,legal_name,registration_number,phone,phone2,whatsapp,sales_email,info_email,address,coverage,mission,vision,values) 
values(1,'VTS Energy & Security','Volt Tech Solutions (Pty) Ltd','2023/259917/7','+27 33 032 2153','+27 82 269 2150','+27822692150','sales@vtsenergysecurity.co.za','info@vtsenergysecurity.co.za','18 Stott Rd, Prestbury, Pietermaritzburg, 3201, South Africa','South Africa | Zimbabwe | Zambia | Botswana | Namibia | Mozambique | Lesotho | Eswatini | Malawi','To provide reliable, affordable, and professional energy and security solutions that keep African businesses and communities powered, protected, and productive.','To become Southern Africa''s most trusted partner for integrated energy resilience and digital protection.','Reliability — We deliver what we promise, on time and to standard. | Trust — We build long-term relationships through honesty and transparency. | Excellence — We use quality products and certified professionals. | Innovation — We embrace modern technology to solve African challenges. | Safety — We protect people, property, and data at all times.')
on conflict(id) do nothing;

insert into public.categories(name,display_order) 
values
  ('Solar',1),
  ('Inverters',2),
  ('Batteries',3),
  ('UPS',4),
  ('CCTV',5),
  ('Access Control',6),
  ('Security Systems',7),
  ('Cybersecurity',8),
  ('Other',9)
on conflict(name) do nothing;

insert into public.services(name,category,description,display_order,image) 
values
  ('Solar power installation','Energy Solutions','VTS specialises in solar power installations designed to support reliable energy continuity across the region.',1,'solar'),
  ('Backup battery systems','Energy Solutions','Backup battery systems that help maintain power availability during interruptions.',2,'battery'),
  ('UPS installation','Energy Solutions','UPS installation for equipment and operations that require protected, uninterrupted power.',3,'ups'),
  ('Inverter systems','Energy Solutions','Inverter systems for practical energy resilience and power management.',4,'inverter'),
  ('Load shedding protection','Energy Solutions','Solutions designed to reduce the operational impact of load shedding.',5,'energy'),
  ('Generator integration','Energy Solutions','Generator integration to support broader backup power strategies.',6,'generator'),
  ('Energy audits','Energy Solutions','Energy audits to assess requirements and identify practical opportunities for improved energy resilience.',7,'audit'),
  ('Energy monitoring','Energy Solutions','Energy monitoring to help clients understand and manage their energy use.',8,'monitor'),
  ('Cybersecurity services','Digital Security Solutions','Cybersecurity services designed to safeguard businesses against modern digital threats.',1,'cyber'),
  ('Network security','Digital Security Solutions','Network security solutions focused on protecting connected business environments.',2,'network'),
  ('Data protection','Digital Security Solutions','Data protection measures designed to help safeguard business information.',3,'data'),
  ('CCTV surveillance','Digital Security Solutions','CCTV surveillance systems for monitoring and protecting business and property environments.',4,'cctv'),
  ('Access control systems','Digital Security Solutions','Access control systems to manage and secure entry to protected areas.',5,'access'),
  ('Biometric security','Digital Security Solutions','Biometric security solutions for controlled and accountable access.',6,'biometric'),
  ('Alarm systems','Digital Security Solutions','Alarm systems for detection and security awareness.',7,'alarm'),
  ('Remote monitoring','Digital Security Solutions','Remote monitoring solutions for visibility over security systems and environments.',8,'remote'),
  ('Security audits','Digital Security Solutions','Security audits to review existing security arrangements and requirements.',9,'security-audit'),
  ('Vulnerability assessments','Digital Security Solutions','Vulnerability assessments to identify potential weaknesses requiring attention.',10,'vulnerability')
on conflict do nothing;

insert into public.products(name,slug,category,short_description,description,price,price_type,image_url,featured,display_order,is_demo) 
values
  ('5kW Hybrid Inverter','5kw-hybrid-inverter','Inverters','DEMO / REPLACE: A configurable hybrid inverter catalogue entry.','Demonstration entry. Replace with VTS-approved product data and verified specifications.',15000,'per unit','inverter.jpg',false,1,true),
  ('Lithium Battery Storage System','lithium-battery-storage-system','Batteries','DEMO / REPLACE: A battery storage catalogue entry.','Demonstration entry. Add verified capacity, chemistry, warranty and safety certifications.',25000,'per unit','battery.jpg',false,2,true),
  ('Solar Panel Package','solar-panel-package','Solar','DEMO / REPLACE: A configurable solar package entry.','Demonstration entry. Replace with exact panel model, quantity, mounting and verified system specs.',35000,'per unit','solar.jpg',false,3,true),
  ('CCTV Surveillance Package','cctv-surveillance-package','CCTV','DEMO / REPLACE: A CCTV catalogue entry.','Demonstration entry. Replace with verified camera, recorder, storage and installation details.',12000,'per unit','cctv.jpg',false,4,true),
  ('Access Control System','access-control-system','Access Control','DEMO / REPLACE: A controlled-entry catalogue entry.','Demonstration entry. Replace with verified access hardware, reader type and installation specifications.',8000,'per unit','access.jpg',false,5,true)
on conflict(slug) do nothing;


-- Correct the central company record when this schema is applied to an existing VTS installation.
update public.site_settings set
  company_name='VTS Energy & Security',
  legal_name='Volt Tech Solutions (Pty) Ltd',
  registration_number='2023/259917/7',
  phone='+27 33 032 2153',
  phone2='+27 82 269 2150',
  whatsapp='+27822692150',
  sales_email='sales@vtsenergysecurity.co.za',
  info_email='info@vtsenergysecurity.co.za',
  address='18 Stott Rd, Prestbury, Pietermaritzburg, 3201, South Africa',
  coverage='South Africa | Zimbabwe | Zambia | Botswana | Namibia | Mozambique | Lesotho | Eswatini | Malawi',
  mission='To provide reliable, affordable, and professional energy and security solutions that keep African businesses and communities powered, protected, and productive.',
  vision='To become Southern Africa''s most trusted partner for integrated energy resilience and digital protection.',
  values='Reliability | Trust | Excellence | Innovation | Safety',
  updated_at=now()
where id=1;

-- Ensure the complete verified service directory exists and corrects the supplied service descriptions.

update public.services set description='VTS specialises in solar power installations designed to support reliable energy continuity across the region.' where name='Solar power installation';
update public.services set description='Backup battery systems that help maintain power availability during interruptions.' where name='Backup battery systems';
update public.services set description='UPS installation for equipment and operations that require protected, uninterrupted power.' where name='UPS installation';
update public.services set description='Inverter systems for practical energy resilience and power management.' where name='Inverter systems';
update public.services set description='Solutions designed to reduce the operational impact of load shedding.' where name='Load shedding protection';
update public.services set description='Generator integration to support broader backup power strategies.' where name='Generator integration';
update public.services set description='Energy audits to assess requirements and identify practical opportunities for improved energy resilience.' where name='Energy audits';
update public.services set description='Energy monitoring to help clients understand and manage their energy use.' where name='Energy monitoring';
update public.services set description='Cybersecurity services designed to safeguard businesses against modern digital threats.' where name='Cybersecurity services';
update public.services set description='Network security solutions focused on protecting connected business environments.' where name='Network security';
update public.services set description='Data protection measures designed to help safeguard business information.' where name='Data protection';
update public.services set description='CCTV surveillance systems for monitoring and protecting business and property environments.' where name='CCTV surveillance';
update public.services set description='Access control systems to manage and secure entry to protected areas.' where name='Access control systems';
update public.services set description='Biometric security solutions for controlled and accountable access.' where name='Biometric security';
update public.services set description='Alarm systems for detection and security awareness.' where name='Alarm systems';
update public.services set description='Remote monitoring solutions for visibility over security systems and environments.' where name='Remote monitoring';
update public.services set description='Security audits to review existing security arrangements and requirements.' where name='Security audits';
update public.services set description='Vulnerability assessments to identify potential weaknesses requiring attention.' where name='Vulnerability assessments';

-- Triggers for updated_at
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at before update on public.products for each row execute function public.touch_updated_at();

drop trigger if exists categories_touch_updated_at on public.categories;
create trigger categories_touch_updated_at before update on public.categories for each row execute function public.touch_updated_at();

drop trigger if exists services_touch_updated_at on public.services;
create trigger services_touch_updated_at before update on public.services for each row execute function public.touch_updated_at();

drop trigger if exists site_settings_touch_updated_at on public.site_settings;
create trigger site_settings_touch_updated_at before update on public.site_settings for each row execute function public.touch_updated_at();
