-- VTS Energy & Security V2 Supabase schema
create extension if not exists pgcrypto;

-- Admin users table
create table if not exists public.admin_users(
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz default now()
);

-- Site settings table
create table if not exists public.site_settings(
  id bigint primary key default 1 check(id=1),
  company_name text not null,
  legal_name text not null,
  registration_number text not null,
  phone text not null,
  phone2 text,
  whatsapp text,
  sales_email text not null,
  info_email text not null,
  address text not null,
  coverage text,
  mission text,
  vision text,
  values text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Categories table
create table if not exists public.categories(
  id bigint generated by default as identity primary key,
  name text unique not null,
  active boolean default true,
  display_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Products table
create table if not exists public.products(
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  category_id bigint references public.categories(id) on delete set null,
  category text,
  short_description text,
  description text not null,
  price numeric,
  price_type text default 'per unit',
  promotion_status text default 'none',
  promotion_type text default 'on_sale',
  original_price numeric,
  sale_price numeric,
  image_url text,
  features jsonb,
  specifications jsonb,
  active boolean default true,
  featured boolean default false,
  display_order int default 0,
  is_demo boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Product promotion migration
alter table public.products add column if not exists specifications jsonb;
alter table public.products add column if not exists promotion_status text default 'none';
alter table public.products add column if not exists promotion_type text default 'on_sale';
alter table public.products add column if not exists original_price numeric;
alter table public.products add column if not exists sale_price numeric;

-- Services table
create table if not exists public.services(
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null check(category in('Energy Solutions','Digital Security Solutions')),
  description text not null,
  display_order int default 0,
  image text,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Admin function
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_users where user_id=auth.uid());
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon,authenticated;

-- Enable RLS
alter table public.admin_users enable row level security;
alter table public.site_settings enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.services enable row level security;

-- RLS Policies
drop policy if exists admin_users_select on public.admin_users;
create policy admin_users_select on public.admin_users for select to authenticated using(user_id=auth.uid());

drop policy if exists settings_public_read on public.site_settings;
create policy settings_public_read on public.site_settings for select to anon,authenticated using(true);
drop policy if exists settings_admin_write on public.site_settings;
create policy settings_admin_write on public.site_settings for update to authenticated using(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');

drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories for select to anon,authenticated using(active=true or lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');
drop policy if exists categories_admin_write on public.categories;
drop policy if exists categories_admin_insert on public.categories;
drop policy if exists categories_admin_update on public.categories;
drop policy if exists categories_admin_delete on public.categories;
create policy categories_admin_insert on public.categories for insert to authenticated with check(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');
create policy categories_admin_update on public.categories for update to authenticated using(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com') with check(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');
create policy categories_admin_delete on public.categories for delete to authenticated using(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');

drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products for select to anon,authenticated using(active=true or lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');
drop policy if exists products_admin_write on public.products;
drop policy if exists products_admin_insert on public.products;
drop policy if exists products_admin_update on public.products;
drop policy if exists products_admin_delete on public.products;
create policy products_admin_insert on public.products for insert to authenticated with check(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');
create policy products_admin_update on public.products for update to authenticated using(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com') with check(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');
create policy products_admin_delete on public.products for delete to authenticated using(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');

drop policy if exists services_public_read on public.services;
create policy services_public_read on public.services for select to anon,authenticated using(active=true or lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');
drop policy if exists services_admin_write on public.services;
drop policy if exists services_admin_insert on public.services;
drop policy if exists services_admin_update on public.services;
drop policy if exists services_admin_delete on public.services;
create policy services_admin_insert on public.services for insert to authenticated with check(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');
create policy services_admin_update on public.services for update to authenticated using(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com') with check(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');
create policy services_admin_delete on public.services for delete to authenticated using(lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');

-- Storage bucket
insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do update set public=true;

drop policy if exists product_images_public_read on storage.objects;
create policy product_images_public_read on storage.objects for select to public using(bucket_id='product-images');

drop policy if exists product_images_authenticated_write on storage.objects;
drop policy if exists product_images_admin_insert on storage.objects;
drop policy if exists product_images_admin_update on storage.objects;
drop policy if exists product_images_admin_delete on storage.objects;
create policy product_images_admin_insert on storage.objects for insert to authenticated with check(bucket_id='product-images' and lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');
create policy product_images_admin_update on storage.objects for update to authenticated using(bucket_id='product-images' and lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com') with check(bucket_id='product-images' and lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');
create policy product_images_admin_delete on storage.objects for delete to authenticated using(bucket_id='product-images' and lower(coalesce(auth.jwt()->>'email',''))='zapifydesigns@gmail.com');

-- Seed data
insert into public.site_settings(id,company_name,legal_name,registration_number,phone,phone2,whatsapp,sales_email,info_email,address,coverage,mission,vision,values) 
values(1,'VTS Energy & Security','Volt Tech Solutions (Pty) Ltd','2023/259917/7','+27 33 032 2153','+27 82 269 2150','+27822692150','sales@vtsenergysecurity.co.za','info@vtsenergysecurity.co.za','18 Stott Rd, Prestbury, Pietermaritzburg, 3201, South Africa','South Africa | Zimbabwe | Zambia | Botswana | Namibia | Mozambique | Lesotho | Eswatini | Malawi','To provide reliable, affordable, and professional energy and security solutions that keep African businesses and communities powered, protected, and productive.','To become Southern Africa''s most trusted partner for integrated energy resilience and digital protection.','Reliability — We deliver what we promise, on time and to standard. | Trust — We build long-term relationships through honesty and transparency. | Excellence — We use quality products and certified professionals. | Innovation — We embrace modern technology to solve African challenges. | Safety — We protect people, property, and data at all times.')
on conflict(id) do nothing;

insert into public.categories(name,display_order) 
values
  ('Solar',1),
  ('Inverters',2),
  ('Batteries',3),
  ('UPS',4),
  ('CCTV',5),
  ('Access Control',6),
  ('Security Systems',7),
  ('Cybersecurity',8),
  ('Other',9)
on conflict(name) do nothing;

insert into public.services(name,category,description,display_order,image) 
values
  ('Solar power installation','Energy Solutions','Professional solar installation planning and delivery for resilient energy systems.',1,'solar'),
  ('Backup battery systems','Energy Solutions','Battery storage solutions for continuous power supply.',2,'battery'),
  ('UPS systems','Energy Solutions','Uninterruptible power supply systems for critical infrastructure.',3,'ups'),
  ('CCTV surveillance','Digital Security Solutions','Professional surveillance system installation and monitoring.',4,'cctv'),
  ('Access control','Digital Security Solutions','Secure entry systems and access management solutions.',5,'access'),
  ('Security monitoring','Digital Security Solutions','24/7 security monitoring and alert response.',6,'monitoring')
on conflict do nothing;

insert into public.products(name,slug,category,short_description,description,price,price_type,image_url,featured,display_order,is_demo) 
values
  ('5kW Hybrid Inverter','5kw-hybrid-inverter','Inverters','DEMO / REPLACE: A configurable hybrid inverter catalogue entry.','Demonstration entry. Replace with VTS-approved product data and verified specifications.',15000,'per unit','inverter.jpg',false,1,true),
  ('Lithium Battery Storage System','lithium-battery-storage-system','Batteries','DEMO / REPLACE: A battery storage catalogue entry.','Demonstration entry. Add verified capacity, chemistry, warranty and safety certifications.',25000,'per unit','battery.jpg',false,2,true),
  ('Solar Panel Package','solar-panel-package','Solar','DEMO / REPLACE: A configurable solar package entry.','Demonstration entry. Replace with exact panel model, quantity, mounting and verified system specs.',35000,'per unit','solar.jpg',false,3,true),
  ('CCTV Surveillance Package','cctv-surveillance-package','CCTV','DEMO / REPLACE: A CCTV catalogue entry.','Demonstration entry. Replace with verified camera, recorder, storage and installation details.',12000,'per unit','cctv.jpg',false,4,true),
  ('Access Control System','access-control-system','Access Control','DEMO / REPLACE: A controlled-entry catalogue entry.','Demonstration entry. Replace with verified access hardware, reader type and installation specifications.',8000,'per unit','access.jpg',false,5,true)
on conflict(slug) do nothing;

-- Triggers for updated_at
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at before update on public.products for each row execute function public.touch_updated_at();

drop trigger if exists categories_touch_updated_at on public.categories;
create trigger categories_touch_updated_at before update on public.categories for each row execute function public.touch_updated_at();

drop trigger if exists services_touch_updated_at on public.services;
create trigger services_touch_updated_at before update on public.services for each row execute function public.touch_updated_at();

drop trigger if exists site_settings_touch_updated_at on public.site_settings;
create trigger site_settings_touch_updated_at before update on public.site_settings for each row execute function public.touch_updated_at();
