import { supabase } from './supabase.js';
import { formatPrice, slugify } from './data.js';
import { ADMIN_EMAIL } from './config.js';

const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let products=[], categories=[], settings, currentImagePath=null, newImageFile=null;
const imgFallback='../assets/images/vts-logo.jpg';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){const el=document.createElement('div');el.className='admin-toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),3200)}
function error(msg){$('#login-error').textContent=msg;$('#login-error').classList.remove('hidden')}
async function isAdmin(){const {data,error}=await supabase.rpc('is_admin');return !error&&data===true}
async function boot(){
  const {data:{session}}=await supabase.auth.getSession(); if(session&&await isAdmin()) showApp(); else showLogin();
  supabase.auth.onAuthStateChange(async(_event,s)=>{if(s&&await isAdmin())showApp();else if(!s)showLogin()});
  $('#login-form').addEventListener('submit',login); $('#logout').addEventListener('click',logout); $('#mobile-menu').addEventListener('click',()=>$('.admin-sidebar').classList.toggle('open'));
  $$('.admin-sidebar nav button').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));
  $$('[data-go]').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.go)));
  $('#add-product').addEventListener('click',()=>openEditor()); $('#product-form').addEventListener('submit',saveProduct); $('#product-image').addEventListener('change',previewImage); $('#clear-image').addEventListener('click',()=>{$('#product-image').value='';newImageFile=null;currentImagePath=null;$('#image-preview').style.backgroundImage='';$('#image-preview').textContent='No image selected'});
  $$('[data-close-editor]').forEach(b=>b.addEventListener('click',closeEditor)); $('#save-company').addEventListener('click',saveCompany);
}
async function login(e){e.preventDefault();$('#login-error').classList.add('hidden');const password=$('#login-password').value;const {error:e1}=await supabase.auth.signInWithPassword({email:ADMIN_EMAIL,password});if(e1){error(e1.message.includes('Invalid')?'Incorrect password. Please try again.':e1.message);return}if(!(await isAdmin())){await supabase.auth.signOut();error('This account is authenticated but is not authorised as a VTS administrator.');return}showApp()}
async function logout(){await supabase.auth.signOut();showLogin()}
function showLogin(){$('#login-view').classList.remove('hidden');$('#app-view').classList.add('hidden');}
async function showApp(){$('#login-view').classList.add('hidden');$('#app-view').classList.remove('hidden');await loadData();showSection('dashboard')}
function showSection(name){$$('.admin-section').forEach(s=>s.classList.add('hidden'));$(`#section-${name}`).classList.remove('hidden');$$('.admin-sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===name));$('#section-title').textContent=name==='company'?'Company Information':name.charAt(0).toUpperCase()+name.slice(1);$('.admin-sidebar').classList.remove('open')}
async function loadData(){
  const [p,c,s,sv]=await Promise.all([supabase.from('products').select('*').order('display_order').order('created_at',{ascending:false}),supabase.from('categories').select('*').eq('active',true).order('display_order'),supabase.from('site_settings').select('*').eq('id',1).single(),supabase.from('services').select('*').eq('active',true).order('display_order')]);
  if(p.error||c.error||s.error){toast('Could not load management data. Check Supabase configuration.');return}
  products=p.data||[];categories=c.data||[];settings=s.data;renderDashboard(sv.data||[]);renderProducts();renderServices(sv.data||[]);fillCompany();fillCategories();
}
function renderDashboard(services){$('#stat-products').textContent=products.length;$('#stat-featured').textContent=products.filter(p=>p.featured).length;$('#stat-energy').textContent=services.filter(s=>s.category==='Energy Solutions').length;$('#stat-security').textContent=services.filter(s=>s.category==='Digital Security Solutions').length;$('#dashboard-recent').innerHTML=products.slice(0,5).map(p=>`<div class="recent-row"><img src="${p.image_url||imgFallback}" alt=""><div><b>${esc(p.name)}</b><small>${esc(p.category||'Other')} · ${formatPrice(p)}</small></div><span class="badge ${p.active?'on':'off'}">${p.active?'Active':'Inactive'}</span></div>`).join('')||'<div class="recent-row">No products yet.</div>'}
function renderProducts(){$('#product-table').innerHTML=products.map(p=>`<tr><td><img class="table-img" src="${p.image_url||imgFallback}" alt=""></td><td><b>${esc(p.name)}</b>${p.is_demo?'<br><small>DEMO / REPLACE</small>':''}</td><td>${esc(p.category||'Other')}</td><td>${formatPrice(p)}</td><td><span class="badge ${p.active?'on':'off'}">${p.active?'Active':'Inactive'}</span></td><td>${p.featured?'Yes':'No'}</td><td><div class="action-row"><button class="mini-btn" data-edit="${p.id}">Edit</button><button class="mini-btn" data-toggle="${p.id}">${p.active?'Disable':'Enable'}</button><button class="mini-btn danger" data-delete="${p.id}">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="7">No products found.</td></tr>';$$('[data-edit]').forEach(b=>b.addEventListener('click',()=>openEditor(products.find(p=>p.id===b.dataset.edit))));$$('[data-toggle]').forEach(b=>b.addEventListener('click',()=>toggleProduct(products.find(p=>p.id===b.dataset.toggle))));$$('[data-delete]').forEach(b=>b.addEventListener('click',()=>deleteProduct(products.find(p=>p.id===b.dataset.delete))))}
function renderServices(rows){$('#service-admin-grid').innerHTML=rows.map(s=>`<article class="service-admin-card"><small>${esc(s.category)}</small><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p></article>`).join('')}
function fillCategories(){const select=$('#product-category');select.innerHTML=categories.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('')}
function fillCompany(){const f=$('#company-form');Object.entries(settings||{}).forEach(([k,v])=>{const el=f.elements[k];if(el)el.value=v??''})}
function openEditor(p){$('#product-editor').classList.remove('hidden');$('#editor-error').classList.add('hidden');$('#product-form').reset();fillCategories();newImageFile=null;currentImagePath=p?.image_path||null;$('#editor-title').textContent=p?'Edit Product':'Add Product';const f=$('#product-form');if(p){f.elements.id.value=p.id;f.elements.name.value=p.name;f.elements.category.value=p.category||categories[0]?.name||'';f.elements.price.value=p.price??'';f.elements.price_type.value=p.price_type;f.elements.short_description.value=p.short_description||'';f.elements.description.value=p.description||'';f.elements.specifications.value=arrayLines(p.specifications);f.elements.features.value=arrayLines(p.features);f.elements.display_order.value=p.display_order??0;f.elements.featured.checked=!!p.featured;f.elements.active.checked=!!p.active;$('#image-preview').style.backgroundImage=`url('${p.image_url||imgFallback}')`;$('#image-preview').textContent=''}else{$('#image-preview').style.backgroundImage='';$('#image-preview').textContent='No image selected';f.elements.active.checked=true}}
function arrayLines(v){if(!Array.isArray(v))return '';return v.map(x=>typeof x==='string'?x:(x.label?`${x.label}: ${x.value||''}`:'')).join('\n')}
function closeEditor(){newImageFile=null;$('#product-editor').classList.add('hidden')}
function previewImage(e){const file=e.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){e.target.value='';$('#editor-error').textContent='Invalid image type. Use JPG, JPEG, PNG or WebP.';$('#editor-error').classList.remove('hidden');return}if(file.size>5*1024*1024){e.target.value='';$('#editor-error').textContent='Image is too large. Maximum size is 5 MB.';$('#editor-error').classList.remove('hidden');return}newImageFile=file;const url=URL.createObjectURL(file);$('#image-preview').style.backgroundImage=`url('${url}')`;$('#image-preview').textContent=''}
async function uploadImage(file){const ext=file.type.split('/')[1].replace('jpeg','jpg');const path=`products/${crypto.randomUUID()}.${ext}`;const {error:e}=await supabase.storage.from('product-images').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'31536000'});if(e)throw e;const {data}=supabase.storage.from('product-images').getPublicUrl(path);return {path,url:data.publicUrl}}
async function saveProduct(e){e.preventDefault();$('#editor-error').classList.add('hidden');const f=e.currentTarget;const name=f.elements.name.value.trim();if(!name){return editorError('Product name is required.')}let price=f.elements.price.value===''?null:Number(f.elements.price.value);if(price!==null&&(!Number.isFinite(price)||price<0))return editorError('Enter a valid non-negative price.');const priceType=f.elements.price_type.value;if(priceType!=='quote'&&price===null)return editorError('A fixed/starting price requires a valid price.');let imagePath=currentImagePath,imageUrl=null;try{if(newImageFile){const uploaded=await uploadImage(newImageFile);imagePath=uploaded.path;imageUrl=uploaded.url;toast('Image uploaded successfully.')}const old=products.find(p=>p.id===f.elements.id.value);const row={name,slug:slugify(name),category:f.elements.category.value,short_description:f.elements.short_description.value.trim(),description:f.elements.description.value.trim(),price,price_type:priceType,image_path:imagePath,image_url:imageUrl||old?.image_url||null,specifications:f.elements.specifications.value.split('\n').map(x=>x.trim()).filter(Boolean),features:f.elements.features.value.split('\n').map(x=>x.trim()).filter(Boolean),featured:f.elements.featured.checked,active:f.elements.active.checked,display_order:Number(f.elements.display_order.value)||0,is_demo:false};let result;if(f.elements.id.value){result=await supabase.from('products').update(row).eq('id',f.elements.id.value).select().single()}else{result=await supabase.from('products').insert(row).select().single()}if(result.error){if(newImageFile&&imagePath&&!old?.image_path)await supabase.storage.from('product-images').remove([imagePath]);if(result.error.code==='23505')return editorError('A product with this name/slug already exists.');throw result.error}if(old?.image_path&&newImageFile&&old.image_path!==imagePath)await supabase.storage.from('product-images').remove([old.image_path]);toast('Product saved successfully.');closeEditor();await loadData()}catch(err){editorError(err.message||'Could not save product.')}}
function editorError(msg){$('#editor-error').textContent=msg;$('#editor-error').classList.remove('hidden')}
async function toggleProduct(p){if(!p)return;const {error:e}=await supabase.from('products').update({active:!p.active}).eq('id',p.id);if(e)return toast('Could not update product status.');toast(`Product ${p.active?'disabled':'enabled'}.`);await loadData()}
async function deleteProduct(p){if(!p)return;if(!confirm(`Are you sure you want to delete this product?\n\n${p.name}`))return;const {error:e}=await supabase.from('products').delete().eq('id',p.id);if(e){toast('Product could not be deleted.');return}if(p.image_path)await supabase.storage.from('product-images').remove([p.image_path]);toast('Product deleted.');await loadData()}
async function saveCompany(){const f=$('#company-form');const row={company_name:f.elements.company_name.value.trim(),legal_name:f.elements.legal_name.value.trim(),registration_number:f.elements.registration_number.value.trim(),phone:f.elements.phone.value.trim(),phone2:f.elements.phone2.value.trim(),whatsapp:f.elements.whatsapp.value.trim(),sales_email:f.elements.sales_email.value.trim(),info_email:f.elements.info_email.value.trim(),address:f.elements.address.value.trim(),coverage:f.elements.coverage.value.trim(),mission:f.elements.mission.value.trim(),vision:f.elements.vision.value.trim(),values:f.elements.values.value.trim()};if(!/^\S+@\S+\.\S+$/.test(row.sales_email)||!/^\S+@\S+\.\S+$/.test(row.info_email))return toast('Please enter valid email addresses.');const {error:e}=await supabase.from('site_settings').update(row).eq('id',1);if(e){toast('Company information could not be saved.');return}toast('Company information saved successfully.');settings={...settings,...row}}
boot();
