import { getSettings, whatsappUrl } from './data.js?v20260914-vts';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function addressCards(addressValue){
  const addresses=String(addressValue||'').split(/\n|\r\n|\s*\|\s*/).map(x=>x.trim()).filter(Boolean);
  const unique=[...new Set(addresses)];
  return unique.map((address,i)=>{const title=/Eveleigh|Boksburg/i.test(address)?'Boksburg Office':'Pietermaritzburg Office';const q=encodeURIComponent(address);return `<article class="location-card"><div class="map-copy"><span class="kicker">${esc(title)}</span><h2>${esc(title.replace(' Office',''))}.</h2><p>${esc(address)}</p><a class="btn btn-dark" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${q}">Open in Maps ↗</a></div><div class="map-frame"><iframe title="VTS Energy & Security ${esc(title)} map" src="https://www.google.com/maps?q=${q}&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div></article>`}).join('');
}
async function boot(){const details=document.querySelector('#contact-details');if(!details)return;try{const s=await getSettings();details.innerHTML=`<div class="contact-detail"><small>Sales</small><a href="mailto:${s.sales_email}">${s.sales_email}</a></div><div class="contact-detail"><small>Information</small><a href="mailto:${s.info_email}">${s.info_email}</a></div><div class="contact-detail"><small>Telephone</small><a href="tel:${s.phone.replace(/\s/g,'')}">${s.phone}</a>${s.phone2?`<br><a href="tel:${s.phone2.replace(/\s/g,'')}">${s.phone2}</a>`:''}</div><div class="contact-detail"><small>WhatsApp</small><a target="_blank" rel="noopener" href="${whatsappUrl(s.whatsapp)}">WhatsApp VTS ↗</a></div>`;
const locations=document.querySelector('#locations'); if(locations)locations.innerHTML=addressCards(s.address);
const form=document.querySelector('#contact-form');const status=document.querySelector('#form-status');form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);if(d.get('website'))return;if(!form.reportValidity())return;const subject=(d.get('subject')||`VTS enquiry from ${d.get('name')}`).trim();const body=`Name: ${d.get('name')}\nCompany: ${d.get('company')||''}\nEmail: ${d.get('email')}\nPhone: ${d.get('phone')}\nSubject: ${subject}\nProduct / Service: ${d.get('product')||''}\n\nMessage:\n${d.get('message')}`;location.href=`mailto:${s.sales_email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;if(status){status.textContent='Your email client should open with the enquiry prepared. If it does not, email '+s.sales_email+' directly.';status.classList.add('is-visible')}})}catch(e){details.innerHTML='<p>Contact information is temporarily unavailable.</p>'}}boot();